In [3]:
import numpy as np
n = np.random.randint(100,150)
r = np.random.randint(5,15)

#construct rank-deficient A
A = np.random.rand(n,n)
u,s,vt = np.linalg.svd(A)
s1 = np.array([10**(-i) for i in range(r)])
s[-r:] = s1
A = u @ np.diag(s) @ vt

def apply_householder(Q, R, col):
    #compute Householder vector
    v = np.zeros(R[col:, col].shape)
    v[0] += np.sign(R[col, col])*np.linalg.norm(R[col:, col])
    v += R[col:,col]

    #apply Householder vector
    k = 2./np.inner(v,v)
    R[col:,col:] -= k * np.outer(v, v @ R[col:,col:])
    Q[:,col:] -= k * np.outer(Q[:,col:] @ v, v)

def not_allowed(*args, **kwargs):
    raise RuntimeError("You called an illegal function.")

import scipy.linalg as sla
for attr in dir(sla):
    setattr(sla, attr, not_allowed)
attrs = dir(np.linalg)
attrs.remove('norm')
for attr in attrs:
    setattr(np.linalg, attr, not_allowed)

print(A.shape)

(131, 131)


In [2]:
import numpy.linalg as la

In [59]:
Q = np.eye(n,n)
R = A.copy()
PP = np.arange(n)
P = np.arange(n)


for i in range(n):
    idx = i+np.argmax(la.norm(R[i:,i:],axis=0))
    PP[i] = idx 
    R[:,[i,idx]] = R[:,[idx,i]] 
    apply_householder(Q,R,i)
for i in range(n):
    tmp = P[i]
    P[i] = P[PP[i]]
    P[PP[i]] = tmp
print(Q@R)
print(A[:,P])

[[0.61117334 0.8913618  0.62356561 ... 0.93986013 0.09426559 0.45166992]
 [0.40659802 0.09359341 0.90237501 ... 0.52612201 0.92020463 0.29768363]
 [0.18365107 0.66831989 0.00700192 ... 0.2635919  0.56116937 0.89595083]
 ...
 [0.20577404 0.82714231 0.90271613 ... 0.0582662  0.35530139 0.92361163]
 [0.30804452 0.86681327 0.16861099 ... 0.80047958 0.97777402 0.26591518]
 [0.1799981  0.7763416  0.12980681 ... 0.73486069 0.5715216  0.11523652]]
[[0.61117334 0.8913618  0.62356561 ... 0.93986013 0.09426559 0.45166992]
 [0.40659802 0.09359341 0.90237501 ... 0.52612201 0.92020463 0.29768363]
 [0.18365107 0.66831989 0.00700192 ... 0.2635919  0.56116937 0.89595083]
 ...
 [0.20577404 0.82714231 0.90271613 ... 0.0582662  0.35530139 0.92361163]
 [0.30804452 0.86681327 0.16861099 ... 0.80047958 0.97777402 0.26591518]
 [0.1799981  0.7763416  0.12980681 ... 0.73486069 0.5715216  0.11523652]]


RuntimeError: You called an illegal function.